#                                                           Developed by Sxntido
#                                                     (Aquatic Studios @ (C) 2016-2024)

name: RenewBlock
version: '1.0'
author: 'Sxntido'

api-version: '1.20'
main: team.aquatic.studios.RenewBlock
description: 'All rights reserved by Aquatic Studios'

commands:
  renewblock:
    description: Command principal the RenewBlock